// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: test.sql

package database

import (
	"context"
)

const getTest = `-- name: GetTest :one
SELECT name FROM test
`

func (q *Queries) GetTest(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getTest)
	var name string
	err := row.Scan(&name)
	return name, err
}
